### ISSUE TITLE
clangd-indexer does not honour directory setting in compile_commands.json

### ISSUE THREAD

**Issue by smhc** [MarkZ3/clang-tools-extra#16]
I hope it is ok to raise this issue here - I couldn't find anywhere else other than the mailing list.

I've tried clangd-indexer for a project which has a common compile_commands.json but is built using many different Makefiles in different directories using plain 'make'.

What I have found is running:
 clangd-indexer -executor=all-TUs compile_commands.json  > clangd.dex

results in many compilation errors due to header files not being found, despite them being in the current directory for the corresponding .cc file. The compile_commands.json specifies the absolute directory which contains both .cc and .h files for each .cc file in question.

Is it possible clangd-indexer is not changing directories to the directory specified in compile_commands.json when trying to compile the TU?

**Comment by smhc** [comment]
I have worked out that this is due to having a compile_commands.json with multiple different directories. clangd-indexer seems to just chdir to the first directory, then use that for all compilation of following TUs.

I posted this to the clang dev mailing list but it may be rejected:

With a directory structure of:

```
./
./abc
./abc/test.h
./abc/test.cc
./def
./def/ytest.h
./def/xtest.cc
./compile_commands.json
```

And a compile_commands.json of:

```javascript
[
    {
        "arguments": [
            "g++",
            "-c",
            "-o",
            "test.o",
            "test.cc"
        ],
        "directory": "/home/test/abc",
        "file": "test.cc"
    },
    {
        "arguments": [
            "g++",
            "-c",
            "-o",
            "xtest.o",
            "xtest.cc"
        ],
        "directory": "/home/test/def",
        "file": "xtest.cc"
    }
]

```
I receive the error:

```
[test]$ clangd-indexer -executor=all-TUs compile_commands.json  > clangd.dex
[1/2] Processing file /home/test/abc/test.cc
[2/2] Processing file /home/test/def/xtest.cc
error: no such file or directory: 'test.cc'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
Error while processing /home/test/abc/test.cc.
Failed to run action on /home/test/abc/test.cc

```
Assuming multiple directories are supported, this looks like it is probably a bug.

**Comment by smhc** [comment]
Passing 

 -execute-concurrency=1

 seems to fix it.

**Comment by MarkZ3** [comment]
Hi! This is my personal fork for Clangd and I am not really active anymore. You should report your issue on the [clangd mailing list](http://lists.llvm.org/cgi-bin/mailman/listinfo/clangd-dev) or file a bug [https://bugs.llvm.org/enter_bug.cgi?product=clang-tools-extra](https://bugs.llvm.org/enter_bug.cgi?product=clang-tools-extra)  with Component: Clangd
